version: "0.2"
allowCompoundWords: true
dictionaries:
  - companies
  - css
  - dotnet
  - docker
  - en_us
  - filetypes
  - fonts
  - html
  - makefile
  - misc
  - node
  - npm
  - people-names
  - powershell
  - python
  - shell
  - softwareTerms
  - typescript
ignoreRegExpList:
  - devcontainer-features
  - extension-recommendations
words:
  # Author Name Components
  - Nate
  - Scherer
  # Repo Name
  - postmodern-helm-chart-copiertemplate
  # Project Name Components
  - Postmodern
  - Helm
  - Chart
  - Copier
  - Template
  # GitHub Username
  - natescherer
  # Code Terms
  - pscore
  - pydoclint
  - pyupgrade
patterns:
  - name: devcontainer-features
    pattern: "\"features\": {(.|\\n)*}"
  - name: extension-recommendations
    pattern: "\"recommendations\": \\[(.|\\n)*]"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
